### ISSUE TITLE
annuaire (carte?)

### ISSUE THREAD

**Issue by cappert** [lyonrb/website#11]
https://github.com/ruby-nord/rubyshops/blob/master/frenchrubyshops.csv
design style : http://lesinternetsduweb.fr/c/lyon

reste le probleme de la modération?

**Comment by pcreux** [comment]
Modération via pull request.

Jette un coup d'œil à vanruby. C'est du Jekyll + CSV.

φ

**Comment by cappert** [comment]
http://vanruby.org/companies.html

**Comment by cappert** [comment]
https://github.com/ruby-nord/rubyshops/blob/master/frenchrubyshops.csv

**Comment by guillaumebriday** [comment]
Reopen if needed
